name: 'Issue Closed Notification'
description: 'Posts a message to Discord channel for issue close events'
inputs:
  discord-webhook-url:
    description: 'Discord Webhook URL'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'award'
  color: 'green'
